"""
routing/ai_router.py
=====================
Final routing step — maps an ExecutionTask + knowledge context to the correct
ProviderManager pipeline.

This is the last layer before the response is generated. It:
  1. Instantiates ProviderManager (which loads all providers lazily)
  2. Builds task-specific prompts from the collected and verified knowledge
  3. Calls the correct manager method
  4. Returns the final reply string
"""

from __future__ import annotations

from colorama import Fore

from engine.execution_planner import ExecutionPlan
from engine.task_classifier import ExecutionTask
from providers.manager import ProviderManager


class AIRouter:
    """
    Stateless router — maps an ExecutionPlan to the correct AI Provider.
    """

    @staticmethod
    def route(
        plan: ExecutionPlan,
        verified_context: str,
        config,
        chat_log: list | None = None,
    ) -> str:
        """
        Route to the correct provider chain and return the AI response.

        Parameters
        ----------
        plan             : ExecutionPlan generated by ExecutionPlanner
        verified_context : The merged and fact-checked context from FactVerifier
        config           : jarvis config module
        chat_log         : session chat log
        """
        mgr = ProviderManager(config)

        print(Fore.MAGENTA + f"⚡ [AI Router]: Executing Task → {plan.task.value}")

        if plan.task == ExecutionTask.READ_LOCAL_REGISTRY:
            from engine.identity_manager import IdentityManager
            registry_data = IdentityManager.get_system_identity()
            return mgr.chat(
                f"You are JARVIS. Use this local registry data to accurately answer the user's question about your identity and capabilities:\n\n{registry_data}\n\nUser: {plan.query}",
                history=chat_log
            )

        elif plan.task == ExecutionTask.EXECUTE_LOCAL_COMMAND:
            # Fallback if command was not intercepted earlier
            return mgr.chat(plan.query, history=chat_log)

        elif plan.task == ExecutionTask.KNOWLEDGE_RETRIEVAL:
            if verified_context:
                prompt = _research_prompt(plan.query, verified_context, config)
            else:
                prompt = plan.query
            return mgr.reasoning(prompt)

        elif plan.task == ExecutionTask.AI_GENERATION:
            # Sub-routing based on Intent to match specific capability pipelines
            from routing.intent_detector import IntentType
            
            if plan.intent == IntentType.CODING_REQUEST:
                prompt = _coding_prompt(plan.query, verified_context)
                return mgr.coding(prompt)
                
            elif plan.intent == IntentType.VISION_REQUEST:
                return mgr.vision(plan.query)
                
            else:
                return mgr.chat(plan.query, history=chat_log)

        return mgr.chat(plan.query, history=chat_log)


# ─────────────────────────────────────────────────────────────────────────────
# Prompt builders
# ─────────────────────────────────────────────────────────────────────────────

def _coding_prompt(user_input: str, verified_context: str) -> str:
    """Enrich a coding request with any available web context."""
    if verified_context:
        return (
            f"Reference material from web:\n{verified_context}\n\n"
            f"Task: {user_input}"
        )
    return user_input


def _research_prompt(user_input: str, verified_context: str, config) -> str:
    """Build a structured synthesis prompt for REASONING queries."""
    return (
        f"You are Jarvis, created by {config.DEVELOPER_ALIAS}. "
        f"Using ONLY the verified research data below, write a clear, well-structured answer. "
        f"Use numbered points or section headings where appropriate. Do not hallucinate.\n\n"
        f"=== VERIFIED RESEARCH DATA ===\n{verified_context}\n\n"
        f"=== USER QUERY ===\n{user_input}\n\n"
        f"=== YOUR ANSWER ==="
    )
